### PR TITLE
Refining error handling

### PR DESCRIPTION
**Pull request by jsdevel**

### CODE REVIEW

**Comment by jsdevel** [comment]
@MugeSo can you give this a review?

**Comment by MugeSo** [comment]
@jsdevel As I answered in https://github.com/kogosoftwarellc/express-openapi/pull/33#issuecomment-205252824
I think error handling should be following:

#### Errors in `Security Requirement Object`
- success when all of elements success
- any of error has status 401 then status is 401
  (all of error has status 403 then status is 403)
- `www-authenticate` are merged
- response body merged into `errors` property or something

#### Errors in `security` property (Array of `Security Requirement Object`):
- success when any of elements success
- any of error has status  403 then status is 403
  (all of error has status 401 then status is 401)
- `www-authenticate` are merged
- response body merged into `errors` property or something

**Comment by MugeSo** [comment]
Unfortunately, `www-authenticate` seems not support logical and condition as far as I read the rfc.

**Comment by jsdevel** [comment]
@MugeSo I believe the current openapi spec doesn't help implementors of security.  My feelings are:

* Users shouldn't mix Basic and Oauth.  Meaning in practice, users should use this:

  ```javascript
  [
    {basicAuth: []},
    {oauthAuth: []}
  ]
  ```

  Basic and API Key may be mixed, as well as Oauth and API Key.

* This implementation will succeed when the security schemes in an object _all_ succeed.
* The first error received in the last security object in the array will fail security.  I don't believe API Key based security uses headers in the response, so it makes sense to make the response singular to a single scheme.

**Comment by jsdevel** [comment]
@MugeSo are you saying that we should _only_ allow `401` or `403`?

**Comment by MugeSo** [comment]
> are you saying that we should only allow 401 or 403?
Yes, unless there is a reason to send status code other than 401 and 403.
I think authenticate error is always one of  them.

**Comment by jsdevel** [comment]
> I think authenticate error is always one of them.

Gotcha.  I think we can limit to that then.

**Comment by MugeSo** [comment]
> Users shouldn't mix Basic and Oauth. 

I think so too. But, worryingly, openapi allows it. We need to think about why it is allowed.
We can forget it when we ensure there is no meaning to allow it. 

> The first error received in the last security object in the array will fail security. I don't believe API Key based security uses headers in the response, so it makes sense to make the response singular to a single scheme.

Please give me clear and detailed explanations.

**Comment by jsdevel** [comment]
@MugeSo what I mean is that we shouldn't merge errors together.

**Comment by MugeSo** [comment]
> We can forget it when we ensure there is no meaning to allow it.

Sorry, this have a meaning only when `express-openapi` aim to support all openapi spec.

**Comment by jsdevel** [comment]
@MugeSo mixing basic and oauth may seemingly be _allowed_ by the spec, but I imagine they weren't able to make them mutually exclusive.  In practice, is it possible for them to co-exist?  I mean, why would a user use oath _and_ basic in a given request?

**Comment by jsdevel** [comment]
@MugeSo opened an issue in the spec https://github.com/OAI/OpenAPI-Specification/issues/620

**Comment by MugeSo** [comment]
@jsdevel Oh, I got it what you mean!!
As you say, `Authorization` header only one in request. Thus, It is impossible to co-exist.
https://tools.ietf.org/html/rfc7235#section-2.1
https://tools.ietf.org/html/rfc7230#section-3.2.2

So, the issue is now:
> I don't believe API Key based security uses headers in the response

It violates RFC that  API key based security don't send `www-authenticate` header when it is only one security scheme and send status code 401.
So, API key based security must send `www-authenticate` header or send status 403.
You think API key based security should do latter, right?

**Comment by jsdevel** [comment]
@MugeSo does it violate security though for api key not to send `www-authenticate`?  I mean, they're expected in either headers _or_ the query string.  Seems for API key the response body should indicate a failure and not the `www-authenticate` header.  Or is `www-authenticate` _required_ with a 401 status code?

**Comment by MugeSo** [comment]
`www-authenticate` is required with 401. 

https://tools.ietf.org/html/rfc7235#section-4.1
>  A server generating a 401 (Unauthorized) response MUST send a
   WWW-Authenticate header field containing at least one challenge.

**Comment by jsdevel** [comment]
@MugeSo nice!  So maybe instead of `headers`, we support `challenge`?  That would support 403.

**Comment by jsdevel** [comment]
```json
cb({
  "status": 401,
  "challenge": "Basic realm=foggy",
  "message": "Unauthorized access to foggy."
});
```

**Comment by MugeSo** [comment]
@jsdevel You mean now `challenge` will be merged? What about status code?

**Comment by jsdevel** [comment]
`statusCode` is `status`.  Yea, I'm thinking `headers` gets ditched for `challenge`.

**Comment by MugeSo** [comment]
Ok, please make commit implemeted it.
Then I'll review again :wink:

**Comment by MugeSo** [comment]
https://tools.ietf.org/html/rfc7235#section-2.1
>  Note: Many clients fail to parse a challenge that contains an
      unknown scheme.  A workaround for this problem is to list well-
      supported schemes (such as "basic") first.

**Comment by jsdevel** [comment]
@MugeSo I think we'll have to leave the entire header value for `www-authenticate` open.  Implementing `challenge` now...

**Comment by jsdevel** [comment]
@MugeSo all done (I hope :smile:).  Can you take a look?

**Comment by MugeSo** [comment]
I think following test cases is needed as a result of this discussion.

```javascript
  securityDefinitions: {
    keyScheme: {
      type: 'apiKey',
      name: 'api_key',
      in: 'header'
    },
    passwordScheme: {
      type: 'basic'
    }
  },

  securityHandlers: {
    keyScheme: function(req, scopes, securityDefinition, cb) {
      cb({
        status: 403,
        message: 'afafaf'
      }, false);
    },
    passwordScheme: function(req, scopes, securityDefinition, cb) {
      cb({
        status: 401,
        challenge: 'Basic realm=foo'
        message: 'afafaf'
      }, false);
    }
  },

  operationSecurity: [
    {
      keyScheme: ['write']
    },
    {
      passwordScheme: []
    }
  ],
```

```javascript
  securityDefinitions: {
    keyScheme: {
      type: 'apiKey',
      name: 'api_key',
      in: 'header'
    },
    passwordScheme: {
      type: 'basic'
    }
  },

  securityHandlers: {
    keyScheme: function(req, scopes, securityDefinition, cb) {
      cb({
        status: 403,
        message: 'afafaf'
      }, false);
    },
    passwordScheme: function(req, scopes, securityDefinition, cb) {
      cb({
        status: 401,
        challenge: 'Basic realm=foo'
        message: 'afafaf'
      }, false);
    }
  },

  operationSecurity: [
     // the order is different form above case.
    // As you know, this order dose not equal to order of callback called in real case.
    // However supposedly this order equals to callback order in test. 
    {
      passwordScheme: []
    },
    {
      keyScheme: ['write']
    }
  ],
```

```javascript
  securityDefinitions: {
    keyScheme: {
      type: 'apiKey',
      name: 'api_key',
      in: 'header'
    },
    passwordScheme: {
      type: 'basic'
    }
  },

  securityHandlers: {
    keyScheme: function(req, scopes, securityDefinition, cb) {
      cb({
        status: 403,
        message: 'afafaf'
      }, false);
    },
    passwordScheme: function(req, scopes, securityDefinition, cb) {
      cb({
        status: 401,
        challenge: 'Basic realm=foo'
        message: 'afafaf'
      }, false);
    }
  },

  operationSecurity: [
    {
      keyScheme: ['write'],
      passwordScheme: []
    }
  ],
```

```javascript
  securityDefinitions: {
    keyScheme: {
      type: 'apiKey',
      name: 'api_key',
      in: 'header'
    },
    passwordScheme: {
      type: 'basic'
    }
  },

  securityHandlers: {
    keyScheme: function(req, scopes, securityDefinition, cb) {
      cb({
        status: 403,
        message: 'afafaf'
      }, false);
    },
    passwordScheme: function(req, scopes, securityDefinition, cb) {
      cb({
        status: 401,
        challenge: 'Basic realm=foo'
        message: 'afafaf'
      }, false);
    }
  },

  operationSecurity: [
    {
      // different order
      passwordScheme: [],
      keyScheme: ['write']
    }
  ],
```

```javascript
  securityDefinitions: {
    keyScheme: {
      type: 'apiKey',
      name: 'api_key',
      in: 'header'
    },
    passwordScheme: {
      type: 'basic'
    }
  },

  securityHandlers: {
    keyScheme: function(req, scopes, securityDefinition, cb) {
      cb({
        status: 401,
        challenge: 'ApiKey realm=foo',
        message: 'afafaf'
      }, false);
    },
    passwordScheme: function(req, scopes, securityDefinition, cb) {
      cb({
        status: 401,
        challenge: 'Basic realm=foo',
        message: 'afafaf'
      }, false);
    }
  },

  operationSecurity: [
    {
      passwordScheme: [],
      keyScheme: ['write']
    }
  ],
```

```javascript
  securityDefinitions: {
    keyScheme: {
      type: 'apiKey',
      name: 'api_key',
      in: 'header'
    },
    passwordScheme: {
      type: 'basic'
    }
  },

  securityHandlers: {
    keyScheme: function(req, scopes, securityDefinition, cb) {
      cb({
        status: 401,
        challenge: 'ApiKey realm=foo',
        message: 'afafaf'
      }, false);
    },
    passwordScheme: function(req, scopes, securityDefinition, cb) {
      cb({
        status: 401,
        challenge: 'Basic realm=foo',
        message: 'afafaf'
      }, false);
    }
  },

  operationSecurity: [
    {
      keyScheme: ['write'],
      passwordScheme: []
    }
  ],
```

```javascript
  securityDefinitions: {
    keyScheme: {
      type: 'apiKey',
      name: 'api_key',
      in: 'header'
    },
    passwordScheme: {
      type: 'basic'
    }
  },

  securityHandlers: {
    keyScheme: function(req, scopes, securityDefinition, cb) {
      cb({
        status: 401,
        challenge: 'ApiKey realm=foo',
        message: 'afafaf'
      }, false);
    },
    passwordScheme: function(req, scopes, securityDefinition, cb) {
      cb({
        status: 401,
        challenge: 'Basic realm=foo',
        message: 'afafaf'
      }, false);
    }
  },

  operationSecurity: [
    {
      passwordScheme: []
    },
    {
      keyScheme: ['write']
    }
  ],
```

```javascript
  securityDefinitions: {
    keyScheme: {
      type: 'apiKey',
      name: 'api_key',
      in: 'header'
    },
    passwordScheme: {
      type: 'basic'
    }
  },

  securityHandlers: {
    keyScheme: function(req, scopes, securityDefinition, cb) {
      cb({
        status: 401,
        challenge: 'ApiKey realm=foo',
        message: 'afafaf'
      }, false);
    },
    passwordScheme: function(req, scopes, securityDefinition, cb) {
      cb({
        status: 401,
        challenge: 'Basic realm=foo',
        message: 'afafaf'
      }, false);
    }
  },

  operationSecurity: [
    {
      keyScheme: ['write']
    },
    {
      passwordScheme: []
    }
  ],
```
```javascript
  securityHandlers: {
    keyScheme: function(req, scopes, securityDefinition, cb) {
      cb({
        status: 403,
        message: 'afafaf'
      }, false);
    },
    passwordScheme: function(req, scopes, securityDefinition, cb) {
      cb({
        status: 403,
        message: 'afafaf'
      }, false);
    }
  },

  operationSecurity: [
    {
      passwordScheme: []
    },
    {
      keyScheme: ['write']
    }
  ],
```

```javascript
  securityDefinitions: {
    keyScheme: {
      type: 'apiKey',
      name: 'api_key',
      in: 'header'
    },
    passwordScheme: {
      type: 'basic'
    }
  },

  securityHandlers: {
    keyScheme: function(req, scopes, securityDefinition, cb) {
      cb({
        status: 403,
        message: 'afafaf'
      }, false);
    },
    passwordScheme: function(req, scopes, securityDefinition, cb) {
      cb({
        status: 403,
        message: 'afafaf'
      }, false);
    }
  },

  operationSecurity: [
    {
      keyScheme: ['write']
    },
    {
      passwordScheme: []
    }
  ],
```

**Comment by jsdevel** [comment]
@MugeSo given that coverage is at 100%, I feel the scenarios are being handled.  Please open a PR if you strongly feel otherwise.

Thanks again for all the great feedback!

**Pull request merged**
